#!/bin/bash
find . -name '*.js' -type f - delete[D[D[D[D[D[F[C[C[B[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D[D[B[C[C[Ce[D[C -delete